[package]
name = "urouter"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/ivabus/urouter"
description = "Small router for (kinda) short domains (static fork of ivabus/aliurl)"


[dependencies]
rocket = "0.5.0-rc.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
url-escape = "0.1.1"
smurf = "0.2.0"